-- Seed AMAC Gouvernance 2.0
-- Sections
INSERT INTO sections (id, nom, ville, responsable, actif) VALUES
(1, 'Abidjan Lagunes', 'Abidjan', 'M. Koffi Kouadio', true),
(2, 'Bouaké Vallée', 'Bouaké', 'Mme Yao Amenan', true),
(3, 'Yamoussoukro Lacs', 'Yamoussoukro', 'M. N''guessan Konan', true),
(4, 'San-Pédro Nawa', 'San-Pédro', 'M. Gnahoré Bailly', true),
(5, 'Korhogo Poro', 'Korhogo', 'M. Silué Sékou', true),
(6, 'Daloa Haut-Sassandra', 'Daloa', 'Mme Traoré Fatoumata', true);

-- Textes
INSERT INTO textes (id, code, titre, date_adoption) VALUES
(1, 'STATUTS', 'Statuts de l''AMAC - Edition 2013', '2013-12-24'),
(2, 'RI', 'Règlement Intérieur de l''AMAC - Edition 2013', '2013-12-24');

-- Reset Auto-increments
SELECT setval('sections_id_seq', 6);
SELECT setval('textes_id_seq', 2);

-- Articles STATUTS
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (1, 1, 1, 'Article 1', 'Constitution', 'Il est constitué entre les adhérents aux présents statuts une association régie par la loi n° 60-315 du 21 septembre 1960 relative aux associations, dénommée Les Amis de la Musique Afro-Cubaine (AMAC).', 'TITRE I - CONSTITUTION - OBJET - DUREE - SIEGE', NULL, 1);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (2, 1, 2, 'Article 2', 'Article 2', 'Contenu standard de l''article 2 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE I - CONSTITUTION - OBJET - DUREE - SIEGE', NULL, 2);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (3, 1, 3, 'Article 3', 'Article 3', 'Contenu standard de l''article 3 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE I - CONSTITUTION - OBJET - DUREE - SIEGE', NULL, 3);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (4, 1, 4, 'Article 4', 'Article 4', 'Contenu standard de l''article 4 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE I - CONSTITUTION - OBJET - DUREE - SIEGE', NULL, 4);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (5, 1, 5, 'Article 5', 'Régime juridique', 'L''association est régie par la loi n° 60-315 du 21 septembre 1960 relative aux associations en Côte d''Ivoire.', 'TITRE I - CONSTITUTION - OBJET - DUREE - SIEGE', NULL, 5);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (6, 1, 6, 'Article 6', 'Moyens d''action', 'Les moyens d''action de l''association sont : l''organisation de concerts, de conférences, de séminaires, d''ateliers de danse et de percussion, et toute autre activité culturelle favorisant la musique afro-cubaine.', 'TITRE II - ACQUISITION ET PERTE DE LA QUALITE DE MEMBRE', NULL, 6);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (7, 1, 7, 'Article 7', 'Article 7', 'Contenu standard de l''article 7 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE II - ACQUISITION ET PERTE DE LA QUALITE DE MEMBRE', NULL, 7);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (8, 1, 8, 'Article 8', 'Article 8', 'Contenu standard de l''article 8 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE II - ACQUISITION ET PERTE DE LA QUALITE DE MEMBRE', NULL, 8);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (9, 1, 9, 'Article 9', 'Article 9', 'Contenu standard de l''article 9 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE II - ACQUISITION ET PERTE DE LA QUALITE DE MEMBRE', NULL, 9);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (10, 1, 10, 'Article 10', 'Article 10', 'Contenu standard de l''article 10 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE II - ACQUISITION ET PERTE DE LA QUALITE DE MEMBRE', NULL, 10);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (11, 1, 11, 'Article 11', 'Article 11', 'Contenu standard de l''article 11 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE II - ACQUISITION ET PERTE DE LA QUALITE DE MEMBRE', NULL, 11);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (12, 1, 12, 'Article 12', 'Article 12', 'Contenu standard de l''article 12 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE II - ACQUISITION ET PERTE DE LA QUALITE DE MEMBRE', NULL, 12);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (13, 1, 13, 'Article 13', 'Perte de la qualité de membre et droit de vote des fondateurs', 'La qualité de membre se perd par démission, exclusion ou décès. Les membres fondateurs ne disposent pas du droit de vote lors des assemblées générales ordinaires et extraordinaires de l''AMAC, disposant uniquement d''une voix consultative.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 13);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (14, 1, 14, 'Article 14', 'Droits et devoirs', 'Chaque membre a le droit de participer aux activités de l''association. Les devoirs des membres s''exercent conformément à l''art. 6 pour la devise et l''identité visuelle de l''association.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 14);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (15, 1, 15, 'Article 15', 'Article 15', 'Contenu standard de l''article 15 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 15);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (16, 1, 16, 'Article 16', 'Article 16', 'Contenu standard de l''article 16 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 16);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (17, 1, 17, 'Article 17', 'Article 17', 'Contenu standard de l''article 17 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE IV - ORGANISATION GENERALE', 'CHAPITRE I - L''ASSEMBLEE GENERALE', 17);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (18, 1, 18, 'Article 18', 'Article 18', 'Contenu standard de l''article 18 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE IV - ORGANISATION GENERALE', 'CHAPITRE I - L''ASSEMBLEE GENERALE', 18);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (19, 1, 19, 'Article 19', 'Article 19', 'Contenu standard de l''article 19 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE IV - ORGANISATION GENERALE', 'CHAPITRE I - L''ASSEMBLEE GENERALE', 19);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (20, 1, 20, 'Article 20', 'Article 20', 'Contenu standard de l''article 20 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE IV - ORGANISATION GENERALE', 'CHAPITRE I - L''ASSEMBLEE GENERALE', 20);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (21, 1, 21, 'Article 21', 'Quorum de l''Assemblée Générale', 'L''assemblée générale ne peut valablement délibérer que si elle réunit les 2/3 de ses membres. Si ce quorum n''est pas atteint, une nouvelle assemblée est convoquée à un mois d''intervalle et peut délibérer quel que soit le nombre de présents.', 'TITRE IV - ORGANISATION GENERALE', 'CHAPITRE I - L''ASSEMBLEE GENERALE', 21);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (22, 1, 22, 'Article 22', 'Droit de procuration', 'Le vote par procuration est autorisé uniquement pour les membres fondateurs empêchés. Nul ne peut être porteur de plus de deux procurations.', 'TITRE IV - ORGANISATION GENERALE', 'CHAPITRE II - L''ORGANISME DE CONTROLE', 22);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (23, 1, 23, 'Article 23', 'Composition et rôle du Comité de Contrôle', 'Le Comité de Contrôle est composé principalement de membres fondateurs. Il est chargé de veiller à l''application des statuts, d''organiser les élections et peut s''autosaisir de tout conflit interne ou suspicion de mauvaise gestion.', 'TITRE IV - ORGANISATION GENERALE', 'CHAPITRE II - L''ORGANISME DE CONTROLE', 23);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (24, 1, 24, 'Article 24', 'Article 24', 'Contenu standard de l''article 24 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE IV - ORGANISATION GENERALE', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 24);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (25, 1, 25, 'Article 25', 'Article 25', 'Contenu standard de l''article 25 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE IV - ORGANISATION GENERALE', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 25);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (26, 1, 26, 'Article 26', 'Composition du Bureau Exécutif National (BEN)', 'Le BEN comprend un Président et 9 autres membres nommés directement par le Président seul, y compris un Vice-Président, un Secrétaire Général et un Trésorier Général.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 26);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (27, 1, 27, 'Article 27', 'Article 27', 'Contenu standard de l''article 27 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 27);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (28, 1, 28, 'Article 28', 'Article 28', 'Contenu standard de l''article 28 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 28);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (29, 1, 29, 'Article 29', 'Majorité requise pour les décisions du BEN', 'Les décisions du Bureau Exécutif National sont prises à la majorité de 51 % des suffrages exprimés. En cas de partage des voix, celle du Président est prépondérante.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 29);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (30, 1, 30, 'Article 30', 'Article 30', 'Contenu standard de l''article 30 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 30);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (31, 1, 31, 'Article 31', 'Article 31', 'Contenu standard de l''article 31 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 31);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (32, 1, 32, 'Article 32', 'Attributions du Président', 'Le Président est le représentant légal de l''association. Il nomme seul les 9 autres membres du BEN et peut déléguer ses pouvoirs au Vice-Président comme prévu à l''article 26 des statuts.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 32);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (33, 1, 33, 'Article 33', 'Article 33', 'Contenu standard de l''article 33 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 33);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (34, 1, 34, 'Article 34', 'Article 34', 'Contenu standard de l''article 34 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 34);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (35, 1, 35, 'Article 35', 'Mandat du Bureau Exécutif', 'Le mandat du Bureau Exécutif est calqué sur celui du Président, soit une durée de 5 ans renouvelable. Il comprend également le 1er Vice-Président qui seconde le Président.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 35);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (36, 1, 36, 'Article 36', 'Article 36', 'Contenu standard de l''article 36 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - ADMINISTRATION ET FONCTIONNEMENT', 'CHAPITRE III - L''ORGANISATION ADMINISTRATIVE', 36);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (37, 1, 37, 'Article 37', 'Création des Sections', 'Il est créé au sein de l''AMAC des sections locales. Chaque section regroupe les membres d''une même localité géographique.', 'TITRE III - DE LA SECTION', NULL, 37);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (38, 1, 38, 'Article 38', 'Aire géographique des Sections', 'Chaque section exerce ses activités sur l''aire géographique définie à l''article 14 des présents statuts, sous la supervision du responsable de section.', 'TITRE III - DE LA SECTION', NULL, 38);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (39, 1, 39, 'Article 39', 'Fonctionnement des Sections', 'Le responsable de section est élu par les membres locaux et rend compte de ses activités au Bureau Exécutif National.', 'TITRE III - DE LA SECTION', NULL, 39);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (40, 1, 40, 'Article 40', 'Article 40', 'Contenu standard de l''article 40 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - RESSOURCES FINANCIERES', NULL, 40);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (41, 1, 41, 'Article 41', 'Article 41', 'Contenu standard de l''article 41 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - RESSOURCES FINANCIERES', NULL, 41);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (42, 1, 42, 'Article 42', 'Article 42', 'Contenu standard de l''article 42 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - RESSOURCES FINANCIERES', NULL, 42);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (43, 1, 43, 'Article 43', 'Article 43', 'Contenu standard de l''article 43 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE V - RESSOURCES FINANCIERES', NULL, 43);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (44, 1, 44, 'Article 44', 'Proposition de modification', 'Les présents statuts ne peuvent être modifiés que sur proposition des 2/3 du Bureau Exécutif ou de l''Assemblée Générale. L''adoption se fait conformément aux conditions de l''article 20 des statuts.', 'TITRE VI - MODIFICATION DES STATUTS ET DISSOLUTION', NULL, 44);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (45, 1, 45, 'Article 45', 'Article 45', 'Contenu standard de l''article 45 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE VI - MODIFICATION DES STATUTS ET DISSOLUTION', NULL, 45);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (46, 1, 46, 'Article 46', 'Révision et vote de modification', 'Toute modification des statuts est adoptée à la majorité simple lors de l''assemblée, conformément aux dispositions de l''article 20.', 'TITRE VI - MODIFICATION DES STATUTS ET DISSOLUTION', NULL, 46);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (47, 1, 47, 'Article 47', 'Article 47', 'Contenu standard de l''article 47 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE VII - DISPOSITIONS FINALES', NULL, 47);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (48, 1, 48, 'Article 48', 'Loi applicable', 'Les présents statuts sont régis par la loi n° 60-315 du 20 septembre 1960 relative aux associations en Côte d''Ivoire.', 'TITRE VII - DISPOSITIONS FINALES', NULL, 48);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (49, 1, 49, 'Article 49', 'Article 49', 'Contenu standard de l''article 49 des statuts de l''AMAC. Conformément aux dispositions en vigueur, les membres s''engagent à respecter l''objet de l''association et à participer activement à ses activités pour promouvoir la musique afro-cubaine.', 'TITRE VII - DISPOSITIONS FINALES', NULL, 49);

-- Articles RI
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (50, 2, 1, 'Article 1', 'Article 1', 'Contenu standard de l''article 1 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE I - ADHESION - COTISATIONS', NULL, 1);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (51, 2, 2, 'Article 2', 'Article 2', 'Contenu standard de l''article 2 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE I - ADHESION - COTISATIONS', NULL, 2);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (52, 2, 3, 'Article 3', 'Article 3', 'Contenu standard de l''article 3 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE I - ADHESION - COTISATIONS', NULL, 3);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (53, 2, 4, 'Article 4', 'Article 4', 'Contenu standard de l''article 4 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE I - ADHESION - COTISATIONS', NULL, 4);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (54, 2, 5, 'Article 5', 'Article 5', 'Contenu standard de l''article 5 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 5);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (55, 2, 6, 'Article 6', 'Frais de carte de membre', 'Les frais d''acquisition de la carte d''adhérent et le montant de la cotisation mensuelle sont fixés par le Bureau Exécutif National et payables d''avance.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 6);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (56, 2, 7, 'Article 7', 'Article 7', 'Contenu standard de l''article 7 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 7);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (57, 2, 8, 'Article 8', 'Article 8', 'Contenu standard de l''article 8 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 8);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (58, 2, 9, 'Article 9', 'Article 9', 'Contenu standard de l''article 9 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 9);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (59, 2, 10, 'Article 10', 'Article 10', 'Contenu standard de l''article 10 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 10);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (60, 2, 11, 'Article 11', 'Article 11', 'Contenu standard de l''article 11 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 11);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (61, 2, 12, 'Article 12', 'Article 12', 'Contenu standard de l''article 12 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 12);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (62, 2, 13, 'Article 13', 'Article 13', 'Contenu standard de l''article 13 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 13);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (63, 2, 14, 'Article 14', 'Article 14', 'Contenu standard de l''article 14 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 14);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (64, 2, 15, 'Article 15', 'Article 15', 'Contenu standard de l''article 15 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE II - DISCIPLINE ET SANCTIONS', NULL, 15);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (65, 2, 16, 'Article 16', 'Procédure d''exclusion', 'En cas d''exclusion d''un membre pour faute grave, la procédure disciplinaire est régie par l''Article 6 ci-dessus, garantissant le droit de parole du membre.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 16);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (66, 2, 17, 'Article 17', 'Article 17', 'Contenu standard de l''article 17 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 17);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (67, 2, 18, 'Article 18', 'Article 18', 'Contenu standard de l''article 18 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 18);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (68, 2, 19, 'Article 19', 'Article 19', 'Contenu standard de l''article 19 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 19);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (69, 2, 20, 'Article 20', 'Scrutins et vote des fondateurs', 'Les membres fondateurs ne disposent pas de droit de vote lors des scrutins de l''assemblée, en conformité avec les statuts.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 20);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (70, 2, 21, 'Article 21', 'Article 21', 'Contenu standard de l''article 21 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 21);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (71, 2, 22, 'Article 22', 'Article 22', 'Contenu standard de l''article 22 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 22);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (72, 2, 23, 'Article 23', 'Article 23', 'Contenu standard de l''article 23 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE III - DROITS AND DEVOIRS DES MEMBRES', NULL, 23);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (73, 2, 24, 'Article 24', 'Délégation de vote', 'Le vote par procuration est restreint aux membres fondateurs empêchés lors de la réunion de l''assemblée générale.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE I - LE BUREAU EXECUTIF', 24);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (74, 2, 25, 'Article 25', 'Composition du Comité de Contrôle', 'Le Comité de Contrôle est composé exclusivement de membres fondateurs, afin de garantir l''indépendance de leur mission d''audit.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE I - LE BUREAU EXECUTIF', 25);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (75, 2, 26, 'Article 26', 'Article 26', 'Contenu standard de l''article 26 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE I - LE BUREAU EXECUTIF', 26);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (76, 2, 27, 'Article 27', 'Article 27', 'Contenu standard de l''article 27 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE I - LE BUREAU EXECUTIF', 27);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (77, 2, 28, 'Article 28', 'Article 28', 'Contenu standard de l''article 28 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE I - LE BUREAU EXECUTIF', 28);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (78, 2, 29, 'Article 29', 'Article 29', 'Contenu standard de l''article 29 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE I - LE BUREAU EXECUTIF', 29);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (79, 2, 30, 'Article 30', 'Intérim de la Présidence', 'En cas d''empêchement temporaire du Président, le Vice-Président assure l''intérim de la présidence du Bureau Exécutif comme prévu à l''article 26 des statuts.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE I - LE BUREAU EXECUTIF', 30);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (80, 2, 31, 'Article 31', 'Article 31', 'Contenu standard de l''article 31 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE II - LE COMITE DE CONTROLE', 31);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (81, 2, 32, 'Article 32', 'Article 32', 'Contenu standard de l''article 32 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE II - LE COMITE DE CONTROLE', 32);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (82, 2, 33, 'Article 33', 'Article 33', 'Contenu standard de l''article 33 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE II - LE COMITE DE CONTROLE', 33);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (83, 2, 34, 'Article 34', 'Article 34', 'Contenu standard de l''article 34 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE IV - FONCTIONNEMENT DES ORGANES', 'CHAPITRE II - LE COMITE DE CONTROLE', 34);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (84, 2, 35, 'Article 35', 'Article 35', 'Contenu standard de l''article 35 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE V - DE LA SECTION LOCALE', NULL, 35);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (85, 2, 36, 'Article 36', 'Article 36', 'Contenu standard de l''article 36 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE V - DE LA SECTION LOCALE', NULL, 36);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (86, 2, 37, 'Article 37', 'Article 37', 'Contenu standard de l''article 37 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE V - DE LA SECTION LOCALE', NULL, 37);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (87, 2, 38, 'Article 38', 'Article 38', 'Contenu standard de l''article 38 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE V - DE LA SECTION LOCALE', NULL, 38);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (88, 2, 39, 'Article 39', 'Article 39', 'Contenu standard de l''article 39 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE V - DE LA SECTION LOCALE', NULL, 39);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (89, 2, 40, 'Article 40', 'Article 40', 'Contenu standard de l''article 40 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE V - DISPOSITIONS FINANCIERES', NULL, 40);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (90, 2, 41, 'Article 41', 'Article 41', 'Contenu standard de l''article 41 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE V - DISPOSITIONS FINANCIERES', NULL, 41);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (91, 2, 42, 'Article 42', 'Article 42', 'Contenu standard de l''article 42 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE V - DISPOSITIONS FINANCIERES', NULL, 42);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (92, 2, 43, 'Article 43', 'Article 43', 'Contenu standard de l''article 43 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE V - DISPOSITIONS FINANCIERES', NULL, 43);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (93, 2, 44, 'Article 44', 'Révision du Règlement Intérieur', 'Les modifications du règlement intérieur sont adoptées conformément à l''article 20 des statuts de l''association.', 'TITRE VII - DISPOSITIONS FINALES', NULL, 44);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (94, 2, 45, 'Article 45', 'Article 45', 'Contenu standard de l''article 45 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE VII - DISPOSITIONS FINALES', NULL, 45);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (95, 2, 46, 'Article 46', 'Article 46', 'Contenu standard de l''article 46 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE VII - DISPOSITIONS FINALES', NULL, 46);
INSERT INTO articles (id, texte_id, numero, numero_affiche, titre, contenu_actuel, titre_parent, chapitre, ordre) VALUES (96, 2, 47, 'Article 47', 'Article 47', 'Contenu standard de l''article 47 du règlement intérieur de l''AMAC. Cet article précise les modalités d''application des statuts pour assurer le bon fonctionnement de l''association au quotidien.', 'TITRE VII - DISPOSITIONS FINALES', NULL, 47);

-- Reset Auto-increments for Articles
SELECT setval('articles_id_seq', 96);

-- Enjeux
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (1, 13, 'contradiction', 'critique', 'Contradiction vote fondateurs : L''article 13 exclut les membres fondateurs du droit de vote lors des scrutins ordinaires et extraordinaires (voix consultative uniquement), mais l''article 22 autorise le vote par procuration exclusivement pour les fondateurs empêchés.', 'Loi n° 60-315, art. 13 & 22 : Droit d''égalité de vote des adhérents dans les associations.', ARRAY[13,22,69,73]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (2, 23, 'risque_gouvernance', 'critique', 'Comité de Contrôle juge et partie : Le comité est composé principalement de membres fondateurs (qui n''ont pas le droit de vote par ailleurs). Il est chargé de veiller à l''application des statuts, d''organiser les élections et de s''autosaisir, risquant un conflit d''intérêts électoral majeur.', 'Principe général du droit des contrats et des associations : impartialité des organes de contrôle électoraux.', ARRAY[23,74]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (3, 26, 'risque_gouvernance', 'critique', 'Concentration excessive des pouvoirs : Le Président nomme à sa discrétion les 9 autres membres du Bureau Exécutif National (BEN) sans aucune validation de l''Assemblée Générale, et leur mandat est aligné sur le sien.', 'Loi n° 60-315 : Représentativité et reddition des comptes des administrateurs.', ARRAY[26,32,35,73,79]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (4, 37, 'incoherence_numerotation', 'majeur', 'Structure cassée : Doublon de "TITRE III". De plus, le titre "De la Section" (art. 37-39) est malencontreusement inséré au beau milieu du Titre V, cassant la hiérarchie logique. Le RI comporte également deux "TITRE V".', 'Insécurité juridique liée à l''impossibilité de citer proprement le texte officiel.', ARRAY[37,38,39,88]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (5, 14, 'renvoi_errone', 'majeur', 'Renvoi erroné en cascade : L''art. 14 renvoie à "l''art. 6" pour la devise (l''art. 6 traite des moyens d''action de l''association, pas de la devise) ; l''art. 32 renvoie à "l''article 26" des statuts pour l''intérim, alors que l''art. 26 ne définit que la composition nominative.', 'Clarté normative et sécurité des statuts.', ARRAY[14,6,32,26,38,65,79]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (6, 48, 'incoherence_numerotation', 'majeur', 'Incohérence de date de la loi de référence : La loi 60-315 est datée du "21 septembre 1960" aux articles 1 et 5, mais du "20 septembre 1960" à l''article 48.', 'Loi n° 60-315 du 21 septembre 1960 relative aux associations.', ARRAY[1,5,48]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (7, 21, 'lacune', 'majeur', 'Quorum de 2/3 irréaliste en pratique : La règle impose un quorum des 2/3, mais autorise sur seconde convocation à 1 mois à délibérer sans aucun quorum. Cela incite à l''absentéisme stratégique et aux décisions par une minorité lors du second tour.', 'Gouvernance démocratique et représentativité.', ARRAY[21]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (8, 46, 'risque_gouvernance', 'majeur', 'Régime de modification statutaire sans majorité qualifiée : Les articles 46 Statuts / 44 RI renvoient l''adoption des révisions à un article de fonctionnement général qui n''exige qu''une majorité simple. Une modification des textes fondateurs à la majorité simple fragilise l''association.', 'Loi n° 60-315 : Robustesse des modifications statutaires.', ARRAY[44,46,93]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (9, 93, 'contradiction', 'majeur', 'Doublon abusif Statuts / Règlement Intérieur : Le RI recopie presque mot pour mot les statuts au lieu de préciser les règlements d''application internes, ce qui génère des contradictions à chaque mise à jour unilatérale.', 'Hiérarchie des normes : le RI est inférieur et ne doit pas répéter les statuts.', ARRAY[44,46,93]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (10, 29, 'modernisation', 'mineur', 'Formulation mathématique erronée : La clause "51 % des suffrages" est techniquement fausse (la majorité absolue se définit par 50 % + 1 voix des suffrages exprimés).', 'Précision de rédaction législative.', ARRAY[29]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (11, 35, 'renvoi_errone', 'mineur', 'Incohérence sur la Vice-Présidence : L''article 26 prévoit "un Vice-Président", mais l''article 35 fait référence au "1er Vice-Président", créant un flou sur le nombre exact de VP.', 'Consistance et clarté des statuts.', ARRAY[26,35]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (12, 55, 'risque_gouvernance', 'mineur', 'Cautionnement électoral inéquitable : Exigence de 50 000 FCFA pour la Présidence et 30 000 FCFA pour le Comité de Contrôle, somme conservée par l''AMAC si le candidat obtient moins de 25% des voix. C''est une barrière injuste d''accès aux candidatures.', 'Équité et liberté de candidature au sein des associations.', ARRAY[55]);
INSERT INTO enjeux (id, article_id, type, gravite, description, base_legale, articles_lies) VALUES (13, 49, 'lacune', 'critique', 'Lacunes de modernisation de la gouvernance 2.0 : Aucune disposition ne prévoit les AG ou votes à distance, le vote électronique, la parité hommes-femmes, l''implication de la diaspora, les droits de la défense disciplinaire ou les archives numériques.', 'Adaptation aux usages numériques et au droit moderne des associations.', ARRAY[49,96]);

-- Reset Auto-increments for Enjeux
SELECT setval('enjeux_id_seq', 13);

-- Questions
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (1, 13, 1, 'Quelle règle de gouvernance appliquer concernant le droit de vote des membres fondateurs ?', 'choix_ab', '{"option_a":"Voix consultative uniquement (Option A) : Supprimer la procuration exclusive et restreindre le droit des fondateurs à un rôle de conseil, sans pouvoir de vote lors des scrutins.","option_b":"Droit de vote plein et généralisé (Option B) : Accorder aux fondateurs les mêmes droits de vote que tout membre actif, et autoriser le vote par procuration pour tous les membres."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (2, 23, 1, 'Comment réformer la composition et le rôle du Comité de Contrôle pour éliminer le risque de conflit d''intérêts ?', 'choix_ab', '{"option_a":"Élection démocratique ouverte (Option A) : Les commissaires aux comptes et membres du comité de contrôle sont élus en AG parmi tous les membres actifs éligibles, sans monopole des fondateurs.","option_b":"Comité de sages fondateurs non-organisateur (Option B) : Maintenir la désignation parmi les fondateurs, mais confier l''organisation logistique des élections à une commission électorale indépendante."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (3, 26, 1, 'Quel mécanisme de contrôle instaurer pour la nomination des membres du Bureau Exécutif National (BEN) ?', 'choix_ab', '{"option_a":"Validation par l''Assemblée Générale (Option A) : Le Président nomme ses membres mais doit soumettre la liste nominative du BEN à l''approbation de l''AG lors de son élection.","option_b":"Pouvoir discrétionnaire du Président (Option B) : Conserver la nomination libre et directe par le Président, mais accorder à l''AG un droit de censure à la majorité qualifiée en cas de manquement."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (4, 37, 1, 'Souhaitez-vous restructurer et uniformiser le statut des sections locales de l''AMAC ?', 'choix_ab', '{"option_a":"Titre de Section autonome (Option A) : Créer un Titre de Section distinct à la fin de l''organisation pour clarifier les rôles et renumérotations.","option_b":"Intégration au fonctionnement général (Option B) : Insérer les règles des sections sous le même chapitre d''administration pour simplifier la structure."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (5, 14, 1, 'Comment corriger les renvois erronés dans les textes (ex: devise à l''article 6, intérim du VP à l''article 26) ?', 'choix_ab', '{"option_a":"Rénovation textuelle explicite (Option A) : Remplacer tous les renvois de numéros par des explications textuelles complètes dans chaque article concerné.","option_b":"Correction automatique et renumérotation (Option B) : Valider la correction logique des renvois via une table de concordance dynamique après adoption de la révision."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (6, 48, 1, 'Quelle date unique de la loi 60-315 doit être retenue dans tous les articles ?', 'choix_ab', '{"option_a":"21 septembre 1960 uniquement (Option A) : Corriger uniformément à la date légale exacte du 21 septembre 1960.","option_b":"Loi n° 60-315 relative aux associations (Option B) : Supprimer la mention des dates dans le corps des articles et ne conserver que le numéro de la loi."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (7, 21, 1, 'Quel quorum réaliste fixer pour la tenue de l''Assemblée Générale de l''AMAC ?', 'choix_ab', '{"option_a":"Quorum à la majorité simple (Option A) : Fixer le quorum à 50% + 1 membre à la première convocation, et 25% à la seconde convocation dans un délai de 15 jours.","option_b":"Quorum à distance (Option B) : Maintenir le quorum des 2/3 mais autoriser expressément la participation et le vote par visioconférence ou voie électronique."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (8, 46, 1, 'Quelle majorité doit être exigée pour toute modification future des statuts de l''AMAC ?', 'choix_ab', '{"option_a":"Majorité qualifiée des 2/3 (Option A) : Exiger le vote positif des deux tiers des membres présents ou représentés en AG.","option_b":"Majorité absolue (Option B) : Exiger le vote positif de la moitié plus un de l''ensemble des adhérents de l''association."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (9, 93, 1, 'Comment structurer le Règlement Intérieur par rapport aux Statuts ?', 'choix_ab', '{"option_a":"RI Opérationnel (Option A) : Supprimer tous les articles recopiés des statuts dans le RI et y inscrire uniquement les procédures pratiques de gestion.","option_b":"Double validation (Option B) : Conserver les textes identiques dans les deux documents avec une clause explicite de primauté des statuts."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (10, 29, 1, 'Comment reformuler la majorité requise de 51% des voix ?', 'choix_ab', '{"option_a":"Majorité absolue (Option A) : Modifier par la formule légale \"majorité absolue des suffrages exprimés\".","option_b":"Majorité des membres présents (Option B) : Remplacer par \"la moitié plus une des voix des membres présents ou représentés\"."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (11, 35, 1, 'Quel nombre de Vice-Présidents l''AMAC doit-elle instituer ?', 'choix_ab', '{"option_a":"Un VP unique (Option A) : Un unique Vice-Président désigné pour seconder et remplacer temporairement le Président.","option_b":"Deux VP (Option B) : Établir un 1er VP (Administration/Organisation) et un 2ème VP (Affaires Culturelles et Artistiques)."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (12, 55, 1, 'Faut-il modifier le régime des cautionnements électoraux des candidats ?', 'choix_ab', '{"option_a":"Suppression totale (Option A) : Remplacer le cautionnement financier par une obligation de parrainage écrit par au moins 10 membres issus de sections différentes.","option_b":"Réduction de cautionnement (Option B) : Ramener la caution à 20 000 FCFA remboursée à partir de 10% des suffrages recueillis."}', true);
INSERT INTO questions (id, article_id, ordre, intitule, type, options, obligatoire) VALUES (13, 49, 1, 'Quelles fonctionnalités modernes intégrer dans la révision finale des statuts ?', 'choix_ab', '{"option_a":"Gouvernance numérique globale (Option A) : Inscrire dans les statuts la légitimité du vote électronique, des AG en ligne, et la création de sections virtuelles pour la diaspora.","option_b":"Due Process disciplinaire (Option B) : Inscrire un droit à la défense avec convocation écrite, délai de 15 jours pour préparer sa défense et commission d''appel indépendante."}', true);

-- Reset Auto-increments for Questions
SELECT setval('questions_id_seq', 13);
